name: Generate and Upload TWRP Device Tree

on:
  workflow_dispatch:

jobs:
  generate_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install python3-pip cpio -y
          pip3 install twrpdtgen

      - name: Find Image
        id: find_image
        run: |
          find . -type f -iname "*.lz4" -exec lz4 -d {} \;
          find . -type f \( -iname "recovery.img" -o -iname "boot.img" \) -exec echo "::set-output name=image_path::{}" \;

      - name: Get Device Codename
        id: get_codename
        run: |
          manufacturer=$(python3 -c "from twrpdtgen.device_tree import DeviceTree; device_tree = DeviceTree('${{ steps.find_image.outputs.image_path }}'); print(device_tree.device['Codename'])")
          echo "::set-output name=codename::$manufacturer"

      - name: Generate Device Tree
        run: |
          python3 -m twrpdtgen ${{ steps.find_image.outputs.image_path }} -o output/${{ steps.get_codename.outputs.codename }}

      # Resto del flujo de trabajo para crear el repositorio, clonarlo y mover los archivos, etc.
