name: Generate and Upload TWRP Device Tree

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: 'Download URL of the image or LZ4 file'
        required: false

jobs:
  generate_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install python3-pip cpio -y
          pip3 install twrpdtgen

      - name: Download Image
        if: github.event.inputs.image_url != ''
        run: |
          curl -o device_image.img ${{ github.event.inputs.image_url }}

      - name: Find Image
        id: find_image
        run: |
          if [ -f "device_image.img" ]; then
            find . -type f -iname "*.lz4" -exec lz4 -d {} \;
            cd $(dirname $(find . -type f \( -iname "recovery.img" -o -iname "boot.img" \)))
            img_file=$(find . -type f \( -iname "recovery.img" -o -iname "boot.img" \))
            if [ -z "$img_file" ]; then
              echo "Error: Image file not found"
              exit 1
            else
              echo "::set-output name=image_path::$img_file"
            fi
          else
            echo "::set-output name=image_path::device_image.img"
          fi

      - name: Get Device Codename
        id: get_codename
        run: |
          manufacturer=$(python3 -c "from twrpdtgen.device_tree import DeviceTree; device_tree = DeviceTree('${{ steps.find_image.outputs.image_path }}'); print(device_tree.device['Codename'])")
          echo "::set-output name=codename::$manufacturer"

      - name: Generate Device Tree
        run: |
          python3 -m twrpdtgen ${{ steps.find_image.outputs.image_path }} -o output/${{ steps.get_codename.outputs.codename }}

      # Rest of the workflow to create the repository, clone it, move files, etc.
